### ISSUE TITLE
章工，我咨询下click house的UDF这边的提交有相关的文档不或者提交的参考代码

### ISSUE THREAD

**Issue by rshw123456** [hczhcz/reflectionpp#1]
章工，我咨询下click house的UDF这边的提交有相关的文档不或者提交的参考代码

**Comment by hczhcz** [comment]
可以参考 arrayReduceInRanges 的 pull request。实现函数体/类型推断，然后注册一下就可以了。如果要提交到开源社区，再要加上测试和文档。
